#!/bin/bash
# chmod ug+x dist
clear

echo 'Creating unlicenced distribution version' $1

rm -rf ./dist
mkdir dist
sleep 1

cat >./dist/version.json <<EOF
    {
      "version": "$1",
      "games": [
        "Pingpong", 
        "SlotMachine"
      ]
    }
EOF


cp ./apps/pwa/.htaccess ./dist
cp ./apps/pwa/favicon.ico ./dist

cp ./apps/react-app/build/index.html ./dist
cp ./apps/react-app/build/asset-manifest.json ./dist
cp -r ./apps/react-app/build/static ./dist

cp ./apps/pwa/logo32.png ./dist
cp ./apps/pwa/logo192.png ./dist
cp ./apps/pwa/logo512.png ./dist
cp ./apps/pwa/manifest.json ./dist
cp ./apps/pwa/opengraph.png ./dist
cp ./apps/pwa/robots.txt ./dist
cp ./apps/pwa/service-worker.js ./dist
cp -r ./apps/pwa/jpg ./dist

mkdir ./dist/games

cp -r ./games/Pingpong/dist ./dist
mv ./dist/dist ./dist/games/Pingpong

cp -r ./games/SlotMachine/dist ./dist
mv ./dist/dist ./dist/games/SlotMachine

echo ""
echo "Done! (created version $1)"

