#!/bin/bash
# chmod ug+x dist
clear

echo 'Creating unlicenced distribution version' $1

rm -rf ./dist
mkdir dist
sleep 1

cat >./dist/version.json <<EOF
    {
      "version": "$1",
      "games": [
        "SlotMachine"
      ]
    }
EOF

cp ./apps/react-app/build/index.html ./dist
cp ./apps/react-app/build/.htaccess ./dist
cp ./apps/react-app/build/favicon.ico ./dist
cp ./apps/react-app/build/asset-manifest.json ./dist
cp ./apps/react-app/build/manifest.json ./dist
cp ./apps/react-app/build/logo32.png ./dist
cp ./apps/react-app/build/logo192.png ./dist
cp ./apps/react-app/build/logo512.png ./dist
cp ./apps/react-app/build/opengraph.png ./dist
cp ./apps/react-app/build/robots.txt ./dist
cp ./apps/react-app/build/service-worker.js ./dist

cp -r ./apps/react-app/build/static ./dist
cp -r ./apps/react-app/build/jpg ./dist

mkdir ./dist/games

cp -r ./games/Pingpong/dist ./dist
mv ./dist/dist ./dist/games/Pingpong

cp -r ./games/SlotMachine/dist ./dist
mv ./dist/dist ./dist/games/SlotMachine

echo ""
echo "Done! (created version $1)"

