#!/bin/bash
# chmod ug+x dist
clear
# Creates the dist folder for deployment

echo 'Creating unlicenced distribution version' $1

rm -rf ./dist
mkdir dist
sleep 1
cat >./dist/version.json <<EOF
    {
      "version": "$1",
      "games": [
        "Pingpong", 
        "SlotMachine"
      ]
    }
EOF

cp ./favicon.ico ./dist
cp ./index.html ./dist

mkdir ./dist/games

cp -r ./games/HelloWorld/dist ./dist
mv ./dist/dist ./dist/games/HelloWorld

# cp -r ./games/CadanoX/dist ./dist
# mv ./dist/dist ./dist/games/CadanoX

cp -r ./react-app/build ./dist
mv ./dist/build ./dist/react-app

echo "Done creating version $1"
