#!/bin/bash
# chmod ug+x start
clear
echo "Starting React & Node Enviroment"

ttab -t 'serve' -d npx serve dist
ttab -t 'watch' -d ./node-app tsc-watch
ttab -t 'node-app' -d ./node-app npm run serve

echo "Godot ready."
