#!/bin/bash
# chmod ug+x start
clear
echo "Starting react-app dev"

ttab -t 'react-app' -d ./apps/react-app npm run start

# ttab -t 'serve' -d npx serve dist
# ttab -t 'watch' -d ./apps/node-app tsc-watch
# ttab -t 'node-app' -d ./apps/node-app npm run serve
